include ../../common/common.mk
include ../../common/loesung.py.mk
include ../../common/generate_vorlage.mk

all: 4-linleastsquares/FORCE

4-linleastsquares/FORCE:
	@$(MAKE) -C 4-linleastsquares

.PHONY: 4-linleastsquares/FORCE
