target-version = "py313"
line-length = 88
extend-exclude = ["python/*.ipynb"]  # let nbqa handle notebooks

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # isort
    "I",
]
ignore = ["E203", "E741", "B905"]

[lint.per-file-ignores]
"exercises-toolbox/8-all/702_Aktivierung_mit_Neutronen/loesung.py" = ["I001"]
"latex/script/mattex*.py" = [
    "E302",  # Expected 2 blank lines, found X
    "E303",  # Too many blank lines
    "E305",  # Expected 2 blank lines after class or function definition
]

fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = true
exclude = ["latex/script/mattex*.py"]