[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "toobox_style"
version = "v1.0.0"

[tool.hatch.build.targets.wheel]
include = ["toolbox_style"]

[project.entry-points."pygments.styles"]
toolbox = "toolbox_style:Toolbox"
