number = "XXX"

rule all:
    input:
        f"build/v{number}.pdf"

rule BUILD:
    input:
        ancient("build")
    output:
        directory("build")
    shell:
        "mkdir -p build"

rule python_0:
    input:
        p = "plot.py"
    output:
        "build/plot.pdf"
    shell:
        "TEXINPUTS=$(pwd)/..: MATPLOTLIBRC=../matplotlibrc python {input.p}"

rule latex:
    input:
        rules.python_0.output,
        p = f"v{number}.tex"
    output:
        f"build/v{number}.pdf"
    shell:
        f"TEXINPUTS=..: BIBINPUTS=..: max_print_line=1048576 latexmk --lualatex --output-directory=build --interaction=nonstopmode --halt-on-error v{number}.tex"

rule CLEAN:
    input:
        "build/"
    shell:
        "rm -rf build"
