include ../../common/common.mk
include ../../common/loesung.py.mk
include ../../common/generate_vorlage.mk

all: 5-readwrite/test.txt

5-readwrite/test.txt: 5-readwrite/loesung2.py.dummy
	@echo "Dies ist ein Beispiel" > 5-readwrite/test.txt
